# Setup the environment for producing the results in the paper
# Activate the environmet to run your code using "source activate my-paper"
# or "activate my-paper" on Windows.
name: my-paper
channels:
    # Prioritize packages from conda-forge to avoid conflicts with defaults
    - conda-forge
    - defaults
dependencies:
    # Lis the dependencies here. It's good practice to specify the exact
    # versions. Use 'conda list' to see your currently installed packages and
    # their versions.
    - python=3.6
    - pip
    - numpy=1.14.0
    - pandas=0.22
    - matplotlib=2.1.2
    - jupyter=1.0.0
    - pytest=3.4.2
    - pytest-cov=2.5.1
    - pylint=1.8.2
    - flake8=3.5.0
    - pip:
        - proselint==0.8.0
